spring:
  config:
    import:
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/portfolio_db}
    username: ${DB_USERNAME:portfolio}
    password: ${DB_PASSWORD:portfolio}
  jpa:
    show-sql: true
